version: '3'

networks:
  web-shop:
    driver: bridge

services:

  grafana:
    image: grafana/grafana
    volumes:
      - "./grafana/definitions:/var/lib/grafana/dashboards"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch
    networks:
      - web-shop

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100
    networks:
      - web-shop

  prometheus:
    build: ./prometheus
    ports:
      - "9090" 
    networks:
      - web-shop

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - web-shop

  shopping-cart:
    build: "shopping-cart/."
    ports:
      - "5555"
    depends_on:
      - "mariadb"
      - "loki"
    networks:
      - web-shop
    restart: on-failure
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push"
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)
 
  products:
    build: "products/."
    ports:
      - "8080:8080"
    environment:
      OTEL_METRICS_EXPORTER: "none"
      OTEL_EXPORTER: "otlp_span"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://agent:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=products"
      JAVA_OPTS: "-javaagent:/opentelemetry-javaagent.jar"
    networks:
      - web-shop
    volumes:
      - ./opentelemetry-javaagent.jar:/opentelemetry-javaagent.jar
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push" 
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)
 
  web-shop:
    build: "web-shop/."
    ports:
      - "80:6666"
    depends_on:
      - "shopping-cart"
    networks:
      - web-shop
    restart: on-failure
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push" 
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)
  
  shop-simulator:
    build: "shop-simulator/."
    depends_on:
      - "web-shop"
    networks:
      - web-shop
    restart: on-failure

  mariadb:
    image: mariadb:latest
    ports:
      - "3306"
    environment:
      MARIADB_ROOT_PASSWORD: myrootpassword
    networks:
      - web-shop
    logging:
      driver: loki
      options:
        loki-url: "http://172.17.0.1:3100/loki/api/v1/push" 
        loki-relabel-config: |
          - action: labelmap
            regex: compose_(service)

  agent:
    image: grafana/agent:latest
    ports:
      - "80"
      - "6832"
      - "55679"
      - "4317:4317"
    volumes:
      - "${PWD}/agent/config.yaml:/etc/agent/agent.yaml"
    networks:
      - web-shop

  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200"
      - "4317"
      - "55680"
      - "55681"
      - "14250"
    command: [ "-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    networks:
      - web-shop
