version: '3'
services:

  grafana:
    image: grafana/grafana
    volumes:
      - "./grafana/definitions:/var/lib/grafana/dashboards"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch

  prometheus:
    build: ./prometheus
    ports:
      - "9090" 
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
  shopping-cart:
    build: "shopping-cart/."
    ports:
      - "5555"
    depends_on:
      - "mariadb"
      - "loki"
  
  web-shop:
    build: "web-shop/."
    ports:
      - "80:6666"
    depends_on:
      - "shopping-cart"
  
  shop-simulator:
    build: "shop-simulator/."
    depends_on:
      - "web-shop"

  mariadb:
    image: mariadb:latest
    ports:
      - "3306"
    environment:
      MARIADB_ROOT_PASSWORD: myrootpassword

  agent:
    image: grafana/agent:latest
    ports:
      - "80"
      - "6832"
      - "55679"
      - "4317"
    volumes:
      - "${PWD}/agent/config.yaml:/etc/agent/agent.yaml"

  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200"
      - "4317"
      - "55680"
      - "55681"
      - "14250"
    command: [ "-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
