
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'web-shop-monitor'

scrape_configs:
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: 'web-shop'
    scrape_interval: 5s

    static_configs:
      - targets: ['web-shop:6666']
        labels:
          group: 'shop'
          service: 'web-shop'

  - job_name: 'shopping-cart'
    scrape_interval: 5s

    static_configs:
      - targets: ['shopping-cart:5555']
        labels:
          group: 'shop'
          service: 'shopping-cart'

  - job_name: 'span-metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['agent:1234']
        labels:
          group: 'shop'
